DELETE FROM bedrock.schema_columns WHERE table_name = 'bc_street';
INSERT INTO bedrock.schema_columns VALUES
('bc_street','objectid',1,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('bc_street','centerline_id',2,NULL,'YES','numeric',NULL,38,10,8,NULL,NULL,NULL),
('bc_street','road_class',3,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('bc_street','street_prefix',4,NULL,'YES','character varying',2,NULL,NULL,NULL,NULL,NULL,NULL),
('bc_street','street_name',5,NULL,'YES','character varying',30,NULL,NULL,NULL,NULL,NULL,NULL),
('bc_street','street_type',6,NULL,'YES','character varying',4,NULL,NULL,NULL,NULL,NULL,NULL),
('bc_street','street_postdirection',7,NULL,'YES','character varying',2,NULL,NULL,NULL,NULL,NULL,NULL),
('bc_street','street_dupe',8,NULL,'YES','character varying',1,NULL,NULL,NULL,NULL,NULL,NULL),
('bc_street','full_street_name',9,NULL,'YES','character varying',32,NULL,NULL,NULL,NULL,NULL,NULL),
('bc_street','speed_limit',10,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('bc_street','lane_count',11,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('bc_street','left_from_address',12,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('bc_street','left_to_address',13,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('bc_street','right_from_address',14,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('bc_street','right_to_address',15,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('bc_street','user_id',16,NULL,'YES','character varying',8,NULL,NULL,NULL,NULL,NULL,NULL),
('bc_street','create_date',17,NULL,'YES','timestamp without time zone',NULL,NULL,NULL,NULL,6,NULL,NULL),
('bc_street','change_date',18,NULL,'YES','timestamp without time zone',NULL,NULL,NULL,NULL,6,NULL,NULL),
('bc_street','lesn',19,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('bc_street','resn',20,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('bc_street','lzip',21,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('bc_street','rzip',22,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('bc_street','lcommcode',23,NULL,'YES','character varying',4,NULL,NULL,NULL,NULL,NULL,NULL),
('bc_street','rcommcode',24,NULL,'YES','character varying',4,NULL,NULL,NULL,NULL,NULL,NULL),
('bc_street','route_id',25,NULL,'YES','character varying',20,NULL,NULL,NULL,NULL,NULL,NULL),
('bc_street','maximo_type',26,NULL,'YES','character varying',30,NULL,NULL,NULL,NULL,NULL,NULL),
('bc_street','maximo_seq_num',27,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('bc_street','asset_code',28,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('bc_street','mrc',29,NULL,'YES','character varying',8,NULL,NULL,NULL,NULL,NULL,NULL),
('bc_street','min_range',30,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('bc_street','max_range',31,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('bc_street','shape',32,NULL,'YES','USER-DEFINED',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
DELETE FROM bedrock.schemas WHERE table_name = 'bc_street'; INSERT INTO bedrock.schemas VALUES ('bc_street',NULL,NOW());
