DELETE FROM bedrock.schema_columns WHERE table_name = 'coa_apd_traffic_stop_data_view';
INSERT INTO bedrock.schema_columns VALUES
('coa_apd_traffic_stop_data_view','shape',1,NULL,'YES','USER-DEFINED',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','agency',2,NULL,'YES','character',4,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','date_occurred',3,NULL,'YES','timestamp without time zone',NULL,NULL,NULL,NULL,6,NULL,NULL),
('coa_apd_traffic_stop_data_view','address',4,NULL,'YES','character varying',75,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','stop_sbi_desc',5,NULL,'YES','character varying',29,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','consent_by_code',6,NULL,'YES','character',4,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','cons_code_desc',7,NULL,'YES','character varying',55,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','rsn_cons_code',8,NULL,'YES','character',4,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','rsn_cons_desc',9,NULL,'YES','character varying',55,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','enf_code_sbi',10,NULL,'YES','character varying',15,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','driver_arrested',11,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','passenger_arrested',12,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','off_phys_resis',13,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','off_use_force',14,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','inj_officer',15,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','inj_driver',16,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','inj_passgr',17,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','search_initiated',18,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','t_search_consent',19,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','t_search_warrant',20,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','t_probable_cause',21,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','t_inc_arrest',22,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','t_pro_frisk',23,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','b_err_susp_bhvr',24,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','b_obs_susp_cband',25,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','b_sus_o_off_info',26,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','b_sus_movemt',27,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','b_infomt_tip',28,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','b_witness_obs',29,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','vehicle_searched',30,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','driver_searched',31,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','passenger_searched',32,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','personal_effects_searched',33,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','no_contraband_found',34,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','geo_beat',35,NULL,'YES','character',4,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','geo_report_area',36,NULL,'YES','character',4,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','traffic_stop_id',37,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_view','sbi_submission_date',38,NULL,'YES','timestamp without time zone',NULL,NULL,NULL,NULL,6,NULL,NULL),
('coa_apd_traffic_stop_data_view','sbi_resubmission_flag',39,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL);
DELETE FROM bedrock.schemas WHERE table_name = 'coa_apd_traffic_stop_data_view'; INSERT INTO bedrock.schemas VALUES ('coa_apd_traffic_stop_data_view',NULL,NOW());
