DELETE FROM bedrock.schema_columns WHERE table_name = 'coa_apd_traffic_stop_data_table';
INSERT INTO bedrock.schema_columns VALUES
('coa_apd_traffic_stop_data_table','agency',1,NULL,'YES','character',4,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','case_number',2,NULL,'YES','character varying',12,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','date_occurred',3,NULL,'YES','timestamp without time zone',NULL,NULL,NULL,NULL,6,NULL,NULL),
('coa_apd_traffic_stop_data_table','address',4,NULL,'YES','character varying',75,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','initial_purpose_of_stop_code',5,NULL,'YES','character',4,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','initial_purpose_of_stop_code_description',6,NULL,'YES','character varying',55,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','initial_purpose_of_stop_sbi_description',7,NULL,'YES','character varying',29,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','consent_by_code',8,NULL,'YES','character',4,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','consent_by_code_description',9,NULL,'YES','character varying',55,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','reason_consent_requested_code',10,NULL,'YES','character',4,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','reason_consent_requested_code_description',11,NULL,'YES','character varying',55,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','enforcement_action_code',12,NULL,'YES','character',4,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','enforcement_action_code_description',13,NULL,'YES','character varying',55,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','enforcement_action_code_sbi_description',14,NULL,'YES','character varying',15,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','driver_arrested',15,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','passenger_arrested',16,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','officer_encountered_physical_resistance',17,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','officer_engaged_in_use_of_force',18,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','injuries_occurred_to_officer',19,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','injuries_occurred_to_driver',20,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','injurires_occurred_to_passenger',21,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','search_initiated',22,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','type_of_search_consent',23,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','type_of_search_search_warrant',24,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','type_of_search_probable_cause',25,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','type_of_search_incident_to_arrest',26,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','type_of_search_protective_frisk',27,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','basis_for_search_erratic_suspicious_behavior',28,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','basis_for_search_observation_of_suspected_contraband',29,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','basis_for_search_suspicious_other_official_information',30,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','basis_for_search_suspicious_movement',31,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','basis_for_search_informant_tip',32,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','basis_for_search_witness_observation',33,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','vehicle_searched',34,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','driver_searched',35,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','passenger_searched',36,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','personal_effects_searched',37,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','no_contraband_found',38,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','geo_beat',39,NULL,'YES','character',4,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','geo_report_area',40,NULL,'YES','character',4,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','geo_x',41,NULL,'YES','numeric',NULL,13,10,2,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','geo_y',42,NULL,'YES','numeric',NULL,13,10,2,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','incident_id',43,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','traffic_stop_id',44,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','sbi_submission_date',45,NULL,'YES','timestamp without time zone',NULL,NULL,NULL,NULL,6,NULL,NULL),
('coa_apd_traffic_stop_data_table','sbi_resubmission_flag',46,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('coa_apd_traffic_stop_data_table','_count',47,NULL,'YES','character varying',200,NULL,NULL,NULL,NULL,NULL,NULL);
DELETE FROM bedrock.schemas WHERE table_name = 'coa_apd_traffic_stop_data_table'; INSERT INTO bedrock.schemas VALUES ('coa_apd_traffic_stop_data_table',NULL,NOW());
