DELETE FROM bedrock.schema_columns WHERE table_name = 'coa_bc_address_master';
INSERT INTO bedrock.schema_columns VALUES
('coa_bc_address_master','objectid',1,NULL,'NO','integer',NULL,32,2,0,NULL,NULL,NULL),
('coa_bc_address_master','civicaddress_id',2,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('coa_bc_address_master','address_x',3,NULL,'YES','numeric',NULL,38,10,8,NULL,NULL,NULL),
('coa_bc_address_master','address_y',4,NULL,'YES','numeric',NULL,38,10,8,NULL,NULL,NULL),
('coa_bc_address_master','address_full',5,NULL,'YES','character varying',40,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','address_number',6,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('coa_bc_address_master','address_unit',7,NULL,'YES','character varying',4,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','address_street_prefix',8,NULL,'YES','character varying',2,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','address_street_name',9,NULL,'YES','character varying',30,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','address_street_type',10,NULL,'YES','character varying',4,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','address_street_postdirection',11,NULL,'YES','character varying',2,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','address_city',12,NULL,'YES','character varying',28,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','address_commcode',13,NULL,'YES','character varying',4,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','address_zipcode',14,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('coa_bc_address_master','location_type',15,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('coa_bc_address_master','address_change_date',16,NULL,'YES','timestamp without time zone',NULL,NULL,NULL,NULL,6,NULL,NULL),
('coa_bc_address_master','maximo_type',17,NULL,'YES','character varying',30,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','maximo_seq_num',18,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('coa_bc_address_master','asset_code',19,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','mrc',20,NULL,'YES','character varying',8,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','water_district',21,NULL,'YES','character varying',8,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','trash_pickup_day',22,NULL,'YES','character varying',10,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','jurisdiction_type',23,NULL,'YES','character varying',150,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','zoning',24,NULL,'YES','character varying',200,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','river_district',25,NULL,'YES','character varying',200,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','centerline_id',26,NULL,'YES','numeric',NULL,19,10,0,NULL,NULL,NULL),
('coa_bc_address_master','location_id',27,NULL,'YES','numeric',NULL,19,10,0,NULL,NULL,NULL),
('coa_bc_address_master','parent_location_id',28,NULL,'YES','numeric',NULL,19,10,0,NULL,NULL,NULL),
('coa_bc_address_master','property_pinnum',29,NULL,'YES','character varying',15,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_pin',30,NULL,'YES','character varying',15,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_pinext',31,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_nmptype',32,NULL,'YES','character varying',150,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_oldpinnum',33,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_update_date',34,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_update_reason',35,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_deeddate',36,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_taxyear',37,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_deedurl',38,NULL,'YES','character varying',254,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_platurl',39,NULL,'YES','character varying',254,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_propcardurl',40,NULL,'YES','character varying',150,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_acreage',41,NULL,'YES','numeric',NULL,38,10,8,NULL,NULL,NULL),
('coa_bc_address_master','property_class',42,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_improved',43,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_exempt',44,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_priced',45,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_totalmarketvalue',46,NULL,'YES','numeric',NULL,38,10,2,NULL,NULL,NULL),
('coa_bc_address_master','property_appraisedvalue',47,NULL,'YES','numeric',NULL,38,10,2,NULL,NULL,NULL),
('coa_bc_address_master','property_taxvalue',48,NULL,'YES','numeric',NULL,38,10,2,NULL,NULL,NULL),
('coa_bc_address_master','property_landuse',49,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_neighborhoodcode',50,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_landvalue',51,NULL,'YES','numeric',NULL,38,10,2,NULL,NULL,NULL),
('coa_bc_address_master','property_buildingvalue',52,NULL,'YES','numeric',NULL,38,10,2,NULL,NULL,NULL),
('coa_bc_address_master','property_improvementvalue',53,NULL,'YES','numeric',NULL,38,10,2,NULL,NULL,NULL),
('coa_bc_address_master','property_appraisalarea',54,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_condounit',55,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_condobuilding',56,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_subname',57,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_sublot',58,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_subblock',59,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_subsect',60,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_township',61,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_stamps',62,NULL,'YES','numeric',NULL,38,10,8,NULL,NULL,NULL),
('coa_bc_address_master','property_instrument',63,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_firedistrict',64,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','property_schooldistrict',65,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','owner_name',66,NULL,'YES','text',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','owner_house_number',67,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','owner_number_suffix',68,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','owner_direction',69,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','owner_street_name',70,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','owner_street_type',71,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','owner_careof',72,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','owner_address',73,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','owner_cityname',74,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','owner_state',75,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','owner_zipcode',76,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','owner_account_number',77,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','longitude_wgs',78,NULL,'YES','numeric',NULL,38,10,8,NULL,NULL,NULL),
('coa_bc_address_master','latitude_wgs',79,NULL,'YES','numeric',NULL,38,10,8,NULL,NULL,NULL),
('coa_bc_address_master','recycling_pickup_district',80,NULL,'YES','character varying',2,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','recycling_pickup_day',81,NULL,'YES','character varying',10,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','gdb_geomattr_data',82,NULL,'YES','bytea',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','shape',83,NULL,'YES','USER-DEFINED',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','unit_type',84,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('coa_bc_address_master','nbrhd_id',85,NULL,'YES','character varying',10,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','nbrhd_name',86,NULL,'YES','character varying',25,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','brushweek',87,NULL,'YES','character varying',2,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','historic_district',88,NULL,'YES','character varying',100,NULL,NULL,NULL,NULL,NULL,NULL),
('coa_bc_address_master','local_landmark',89,NULL,'YES','character varying',50,NULL,NULL,NULL,NULL,NULL,NULL);
DELETE FROM bedrock.schemas WHERE table_name = 'coa_bc_address_master'; INSERT INTO bedrock.schemas VALUES ('coa_bc_address_master','Master address table',NOW());
