DELETE FROM bedrock.schema_columns WHERE table_name = 'gl_budget';
INSERT INTO bedrock.schema_columns VALUES
('gl_budget','account_type',1,NULL,'YES','character',1,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_budget','account_status',2,NULL,'YES','character',1,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_budget','fund_name',3,NULL,'YES','character varying',30,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_budget','function_name',4,NULL,'YES','character varying',30,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_budget','department_name',5,NULL,'YES','character varying',30,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_budget','division_name',6,NULL,'YES','character varying',30,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_budget','costcenter_name',7,NULL,'YES','character varying',30,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_budget','grant_name',8,NULL,'YES','character varying',30,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_budget','organization_name',9,NULL,'YES','character',30,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_budget','object_name',10,NULL,'YES','character',30,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_budget','project_name',11,NULL,'YES','character varying',35,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_budget','year',12,NULL,'YES','smallint',NULL,16,2,0,NULL,NULL,NULL),
('gl_budget','proposed_budget',13,NULL,'YES','numeric',NULL,13,10,2,NULL,NULL,NULL),
('gl_budget','adopted_budget',14,NULL,'YES','numeric',NULL,13,10,2,NULL,NULL,NULL),
('gl_budget','fund_id',15,NULL,'YES','character varying',10,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_budget','function_id',16,NULL,'YES','character varying',10,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_budget','department_id',17,NULL,'YES','character varying',10,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_budget','division_id',18,NULL,'YES','character varying',10,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_budget','costcenter_id',19,NULL,'YES','character varying',10,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_budget','grant_id',20,NULL,'YES','character varying',10,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_budget','organization_id',21,NULL,'YES','character varying',8,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_budget','object_id',22,NULL,'YES','character varying',6,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_budget','project_id',23,NULL,'YES','character varying',10,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_budget','full_account_id',24,NULL,'YES','character',55,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_budget','charcode_name',25,NULL,'YES','character varying',20,NULL,NULL,NULL,NULL,NULL,NULL);
DELETE FROM bedrock.schemas WHERE table_name = 'gl_budget'; INSERT INTO bedrock.schemas VALUES ('gl_budget','Master budget table',NOW());
