DELETE FROM bedrock.schema_columns WHERE table_name = 'gl_master';
INSERT INTO bedrock.schema_columns VALUES
('gl_master','account_type',1,NULL,'YES','character',1,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_master','account_status',2,NULL,'YES','character',1,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_master','fund_name',3,NULL,'YES','character varying',30,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_master','function_name',4,NULL,'YES','character varying',30,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_master','department_name',5,NULL,'YES','character varying',30,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_master','division_name',6,NULL,'YES','character varying',30,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_master','costcenter_name',7,NULL,'YES','character varying',30,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_master','grant_name',8,NULL,'YES','character varying',30,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_master','organization_name',9,NULL,'YES','character',30,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_master','object_name',10,NULL,'YES','character',30,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_master','project_name',11,NULL,'YES','character varying',35,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_master','year',12,NULL,'YES','integer',NULL,32,2,0,NULL,NULL,NULL),
('gl_master','original_budget',13,NULL,'YES','numeric',NULL,13,10,2,NULL,NULL,NULL),
('gl_master','revised_budget',14,NULL,'YES','numeric',NULL,13,10,2,NULL,NULL,NULL),
('gl_master','actual',15,NULL,'YES','numeric',NULL,13,10,2,NULL,NULL,NULL),
('gl_master','memo',16,NULL,'YES','numeric',NULL,13,10,2,NULL,NULL,NULL),
('gl_master','cy_encumbrances',17,NULL,'YES','numeric',NULL,13,10,2,NULL,NULL,NULL),
('gl_master','lifetime_original_budget',18,NULL,'YES','numeric',NULL,13,10,2,NULL,NULL,NULL),
('gl_master','lifetime_revised_budget',19,NULL,'YES','numeric',NULL,13,10,2,NULL,NULL,NULL),
('gl_master','life_transfers_in',20,NULL,'YES','numeric',NULL,13,10,2,NULL,NULL,NULL),
('gl_master','life_transfers_out',21,NULL,'YES','numeric',NULL,13,10,2,NULL,NULL,NULL),
('gl_master','fund_id',22,NULL,'YES','character varying',10,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_master','function_id',23,NULL,'YES','character varying',10,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_master','department_id',24,NULL,'YES','character varying',10,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_master','division_id',25,NULL,'YES','character varying',10,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_master','costcenter_id',26,NULL,'YES','character varying',10,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_master','grant_id',27,NULL,'YES','character varying',10,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_master','organization_id',28,NULL,'YES','character varying',8,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_master','object_id',29,NULL,'YES','character varying',6,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_master','project_id',30,NULL,'YES','character varying',10,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_master','full_account_id',31,NULL,'YES','character',55,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_master','charcode_name',32,NULL,'YES','character varying',20,NULL,NULL,NULL,NULL,NULL,NULL),
('gl_master','is_budgetary',33,NULL,'YES','character',1,NULL,NULL,NULL,NULL,NULL,NULL);
DELETE FROM bedrock.schemas WHERE table_name = 'gl_master'; INSERT INTO bedrock.schemas VALUES ('gl_master','Master general ledger history',NOW());
